/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
 * Generated on: 19-Feb-2015 16:31:50
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 4
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2014a\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 9
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,2,1 };
const double NUM[MWSPT_NSEC][3] = {
  {
     0.9926614461523,                 0,                 0 
  },
  {
                   1,   -1.999849907196,                 1 
  },
  {
     0.9801507806822,                 0,                 0 
  },
  {
                   1,   -1.999903473405,                 1 
  },
  {
     0.9716757630443,                 0,                 0 
  },
  {
                   1,   -1.999970271385,                 1 
  },
  {
     0.9842186395767,                 0,                 0 
  },
  {
                   1,                -1,                 0 
  },
  {
                   1,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,2,1 };
const double DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.984663489337,   0.9858333039327 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.959702965166,   0.9608055469452 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.942823003374,   0.9438511622278 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.9684372791534,                 0 
  },
  {
                   1,                 0,                 0 
  }
};
