/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
 * Generated on: 26-Feb-2015 09:51:37
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2014a\extern\include\tmwtypes.h 
 */

namespace filterFromMatlab1 {

#define MWSPT_NSEC 11
    const int NL[MWSPT_NSEC] = {1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1};
    double NUM[MWSPT_NSEC][3] = {
            {
                    0.9846526035452, 0, 0
            },
            {
                    1, -1.994456661135, 1
            },
            {
                    0.9600553933832, 0, 0
            },
            {
                    1, -1.995487622573, 1
            },
            {
                    0.9400584284873, 0, 0
            },
            {
                    1, -1.997156880864, 1
            },
            {
                    0.9260266854734, 0, 0
            },
            {
                    1, -1.998827534523, 1
            },
            {
                    0.9188090121331, 0, 0
            },
            {
                    1, -1.999860753716, 1
            },
            {
                    1, 0, 0
            }
    };
    const int DL[MWSPT_NSEC] = {1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1};
    double DEN[MWSPT_NSEC][3] = {
            {
                    1, 0, 0
            },
            {
                    1, -1.960080145527, 0.9730720056083
            },
            {
                    1, 0, 0
            },
            {
                    1, -1.912105004923, 0.9237844363247
            },
            {
                    1, 0, 0
            },
            {
                    1, -1.873845524815, 0.8837154910274
            },
            {
                    1, 0, 0
            },
            {
                    1, -1.8474212358, 0.8555997717744
            },
            {
                    1, 0, 0
            },
            {
                    1, -1.833970415015, 0.8411376927769
            },
            {
                    1, 0, 0
            }
    };


}